### ISSUE TITLE
Resolve `<module-name>/index.js`

### ISSUE THREAD

**Issue by runspired** [dot-build/rollup-plugin-includepaths#1]
Currently `index` is only attempted to be resolved for relative file paths, not for paths beginning in the source directory.

https://github.com/dot-build/rollup-plugin-includepaths/blob/master/src/plugin.js#L189

I was able to solve this temporarily by adding `\/index.js` as an extension like so:

```js
function makePlugin(path) {
  var includePathOptions = {
    include: {},
    paths: [path],
    external: [],
    extensions: ['.js', '.json', '\/index.js']
  };

  return includePaths(includePathOptions);
}
```

**Comment by darlanalves** [comment]
Hello @runspired! I'm not sure if I get your use case, so correct me here if I'm wrong:

```js
// file a.js placed on file-a/a.js
import 'b';
```

```js
// file index.js placed on b/index.js
// ...
```

Is this the case? 

I'm actually wondering if this `/index.js` case is good to keep on plugin. It doubles the amount of I/O access and makes the plugin even more slow. I added it to support these imports inside a node module I needed.

Anyway, if I'm not mistaken, I just need to add one more check in this line
https://github.com/dot-build/rollup-plugin-includepaths/blob/master/src/plugin.js#L159

**Comment by nilssolanki** [comment]
I would appreciate this feature as well (coming from webpack, this was really useful), even if it slightly alters the performance.

**Comment by runspired** [comment]
@darlanalves yes, my specific usage is that a different build step has already pushed all needed modules into a `tmp` directory. So `import 'b';` which should resolve to `<dir>/b/index.js` is unfound.

Beyond that though, it's also how most imports from node_modules are going to behave. The main file is very often an `index`.

**Comment by darlanalves** [comment]
Ok folks! Sorry the delay, busy week. So, I have this layout:

```
app.js
tmp/file-a/a.js
tmp/b/index.js
```

```js
// app.js
import {A} from 'file-a/a';

export default A;
```

```js
// tmp/file-a/a.js

import B from 'b';

class A extends B {}

export { A };
```

```js
// /tmp/b/index.js
class B {}

export default B;
```

... and this config file:

```js
import includePaths from 'rollup-plugin-includepaths';

let includePath = includePaths({
    paths: ['tmp'],
    extensions: ['.js']
});

export default {
    entry: 'app.js',
    format: 'cjs',
    dest: 'bundle.js',
    plugins: [includePath]
};
```

With that, B was included for A, and both included on final bundle. Published a new version on npm already. Let me know if it fixes your issues.
