### ISSUE TITLE
does not load module index with other extensions

### ISSUE THREAD

**Issue by pedrotainha** [dot-build/rollup-plugin-includepaths#14]
in function searchProjectModule, we only got:

```
newPath = this.resolvePath(path.resolve(workingDir, includePath[i], file, 'index.js'), false);
            if (newPath) return newPath;
```

We should have this dynamic with the extensions that are set by the user in plugin.

In my case i also needed:
```
newPath = this.resolvePath(path.resolve(workingDir, includePath[i], file, 'index.jsx'), false);
            if (newPath) return newPath;
```

I sugest the code like this:

```
// #1 - also check for 'path/to/file' + 'index.[file extension]'
            for (let j = 0, jj = this.extensions.length; j < jj ; j++) {
                newPath = this.resolvePath(path.resolve(workingDir, includePath[i], file, 'index'+this.extensions[j]), false);
                if (newPath) return newPath;
            }
```

thank you

**Comment by darlanalves** [comment]
Added on v0.1.7

Let me know if it solves the issue for you. If it does, feel free to close the ticket.

Thanks for your feedback and contribution 👍

**Comment by pedrotainha** [comment]
Hi, sorry didn't add time to test as i never get back to the project i had this situation. thank you for adding.
