### ISSUE TITLE
question: How to make it work with eslint?

### ISSUE THREAD

**Issue by vyorkin** [dot-build/rollup-plugin-includepaths#15]
I mean this rule: [import/no-extraneous-dependencies](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md)

for example if I have the following project structure:
```
▾ src/
    index.js
    InputStream.js
    TokenStream.js
▾ test/
    TokenStream_test.js
```

and then in my `test/TokenStream_test.js` I have this import:

```
import TokenStream from 'TokenStream';
```

which results in error:

```
'TokenStream' should be listed in the project's dependencies. Run 'npm i -S TokenStream' to add it (import/no-extraneous-dependencies) [javascript/eslint]
```

**Comment by stalkerg** [comment]
For eslint you should use special plugins like eslint-import-resolver-babel-module and config in .eslint:
```json
{
"settings": {
        "import/resolver": {
            "babel-module": {
                "root": [
                    "./src"
                ],
                "extensions": [
                    ".js"
                ]
            }
        }
    }
}
```
