### ISSUE TITLE
something broken - const includePaths = require(rollup-plugin-includepaths) is not a function

### ISSUE THREAD

**Issue by joelchu** [dot-build/rollup-plugin-includepaths#17]
it was working all fine until this morning, I setup a new project with this plugin. 

```javascript 
...
const includePaths = require('rollup-plugin-includepaths');
...

const createRollupStack = (build) =>
 {
     const outFileName = (build) ? 'bundle.min.js' : 'bundle.js';
     let plugins = [
          // so we could include file with a relative path
          includePaths({
              include: {},
              paths: [yeoman.script] , //nbConfig.includePaths ,
              external: [],
              extensions: nbConfig.extensions
          }),
          json(),
          riot(),
          nodeResolve({
              jsnext: true,
              main: true,
              browser: true
          }),
          // this is not working strangely the __commonJs method inject at first run
          // then when the file re-compile the method disappeared.
          commonJs({
              include: 'node_modules/**'
              // ignoreGlobal: true
          }),
          babel() // {exclude: 'node_modules/**'}
     ];
     if (build) {
         plugins.push(
             uglify({}, minify)
         );
     }
     let stack = [
         rollupStream({
             entry: join(yeoman.script , 'bundle.js'),
             format: 'iife',
             cache: cache,
             plugins: plugins,
             globals: globalLibs,
          	external: externalLibs
             // sourceMap: build ? false : true // <-- @BUG the source map never generate correctly!
         }),
         /*
         @BUG When enable cache, only first run compile correctly and the second time failed
              with missing commonJs function
         .on('bundle' , function(bundle)
         {
             if (!build) {
                 cache = bundle;
             }
         }),
         */
         vinylSource(outFileName)
     ];
     if (build) {
         stack.push(
             gulp.dest(
                 join(yeoman.dest , 'app' , 'scripts')
             )
         );
     }
     else {
         const devStack = [
             // see @BUG
             // vinylBuffer(),
             // sourcemaps.init({loadMaps:true}),
             // sourcemaps.write('.'),
             gulp.dest(join(yeoman.dev  , 'scripts'))
         ];
         stack = stack.concat(devStack);
     }
     return stack;
 };
```

The error I got is 

```

[14:22:53] TypeError: includePaths is not a function
    at createRollupStack (/Users/joelck/Dropbox/DEV/HALO/Main/Halo.Dashboard/desktop/gulpfile.js:73:11)
    at Gulp.gulp.task (/Users/joelck/Dropbox/DEV/HALO/Main/Halo.Dashboard/desktop/gulpfile.js:202:10)
    at module.exports (/Users/joelck/Dropbox/DEV/HALO/Main/Halo.Dashboard/desktop/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/joelck/Dropbox/DEV/HALO/Main/Halo.Dashboard/desktop/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/joelck/Dropbox/DEV/HALO/Main/Halo.Dashboard/desktop/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/joelck/Dropbox/DEV/HALO/Main/Halo.Dashboard/desktop/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/Users/joelck/Dropbox/DEV/HALO/Main/Halo.Dashboard/desktop/node_modules/run-sequence/index.js:86:16)
    at Gulp.onTaskEnd (/Users/joelck/Dropbox/DEV/HALO/Main/Halo.Dashboard/desktop/node_modules/run-sequence/index.js:75:5)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)

```

I tried to console.log out to see what is return from the require call.

```

console.log('includePaths' , includePaths);

includePaths { default: [Function: plugin] }

```

Any structure change in the code?

**Comment by joelchu** [comment]
I roll it back to v0.1.6 and it works. 

And the console.log out becomes 

```

includePaths function plugin(options) {
    var resolver = new RollupIncludePaths(options);

    return {
        resolveId: function resolveId(file, origin) {
            return resolver.resolveId(file, origin);
        },

        options: function options(_options2) {
            return resolver.options(_options2);
        }
    };
}

```

hope this help.

**Comment by ejmurra** [comment]
I also ran into this. The problem is that the package now exports as a default export. To fix, you can change your code to `require("rollup-plugin-includepaths").default`.

@darlanalves I hope you'll consider releasing breaking changes as a major version update in the future. The reason is, `npm install --save rollup-plugin-includepaths` will automatically add a caret to the dependency in the `package.json` and anyone who installs from the `package.json` will download any minor patches (which in this case includes a breaking change).

I understand that this package hasn't hit version 1 yet but the code has been stable for a few months now and has a user base of at least a few thousand a month according to npm. If it's just not ready for a 1.0.0 release, I urge you to create some milestones for what needs to be finished before it can get a stable release. I'd be happy to contribute!

**Comment by darlanalves** [comment]
Hello guys!

First of all, sorry for the breaking release version 😞 
I wrote this plugin to suffice a need I had and was sort of a quick solution. I have to proper release/build tasks in place yet. Because of that, I'm just copying/pasting the ES6 code into babeljs.io site for ES5 version and probably I screwed up the compatibility.

I just pushed a new patch that restores the CommonJS exports value. (v0.2.1)

**Comment by joelchu** [comment]
I changed to 

     const includePaths = require('rollup-plugin-includepaths').default;

Same error. Now the console.log show just undefined. 

The version is 0.2.1

**Comment by joelchu** [comment]
I read your ES6 code. really don't understand what you are trying to do there. 

You export a named function plugin.

Then re-export an object with two key named function. 

If you try to do a named export all you have to do is 

      export default function1 // <-- then the commonJs will pick up this default 
      export function2; // the destructuring will pick up in ES6 with the {function2} 

Could you explain a little bit which bit is the original function call? Thanks

**Comment by ejmurra** [comment]
@joelchu, v0.1.7 - 0.2.0 needs `require("rollup-plugin-includepaths").default`. v0.2.1 has been reverted to just `require("rollup-plugin-includepaths")`
