### ISSUE TITLE
Any interest in supporting TypeScript at some point?

### ISSUE THREAD

**Issue by toranb** [dot-build/rollup-plugin-includepaths#23]
I was doing some TypeScript a few weeks back and noticed my `.ts` files would have a `.js` appended to them.

https://github.com/dot-build/rollup-plugin-includepaths/blob/master/src/plugin.es5.js#L145

Is legit TypeScript support a thing anyone else might be interested in or no?

**Comment by brettinternet** [comment]
Were you able to get this plugin to work with Typescript?
