### ISSUE TITLE
`resolveCachedPath` ignores `origin`

### ISSUE THREAD

**Issue by fatfisz** [dot-build/rollup-plugin-includepaths#3]
Currently `resolveCachedPath` looks like this:
```
if (id in this.cache) {
  return this.cache[id];
}

return false;
```

So in this situation:
```
// directory-a/script.js
import value from './value';
export default value;
```
```
// directory-b/script.js
import value from './value';
export default value;
```
the `value` will be incorrect in one case, because exactly one of `directory-a/value.js` and `directory-b/value.js` will be cached (as `./value.js`). That is why the origin also has to be taken into consideration.

@darlanalves I'm currently looking into this, do you see a chance to get this out quickly after it is patched?

**Comment by fatfisz** [comment]
@darlanalves I think it should be ok to cache the file name along with the dirname of the origin.

The other idea I have is ignoring relative paths altogether, but that could possibly break some code. Still, I think that relative paths are outside the scope of what `rollup-plugin-includepaths` should be doing (because relative paths are already handled ok by other resolvers), but that's only an opinion.

**Comment by darlanalves** [comment]
Hello buddy :) 

Nice spotting here! I'd never notice this bug.

I think it will break some build to completely remove the relative path resolution. Both "absolute" and relative path search are not only reduced to find a given path, but check for alternatives of it, e.g checking for a missing file extension. Removing the feature altogether would lead to a duplication of the plugin just for relative path search.

The simplest solution IMO would be just disable the caching of relative paths. That solves the issue while keeping the feature. 

Now, caching the relative paths along with the origin could be better to speedup the search in cases that several modules require one common module in the same folder. It's really ease to add that too, in the method that resolves from cache.

What about this instead?
https://github.com/dot-build/rollup-plugin-includepaths/commit/0b24e60c77c67f31a1e0ecda8c94b3c2487a2e0e#diff-a4f485aa834ca5b3c24819fceb39c56fL62

**Comment by fatfisz** [comment]
No problem, that works too and doesn't break anything. Thanks for the quick reply and a fix!

Btw. would you mind adding any packages that you are using to build the `src/plugin.es5.js` version of the plugin? That would be very helpful to potential contributors.

Also, would you consider using `Map` for the cache object while we are at that? It's better to use that instead of the plain object for dictionary-like data structures.

**Comment by darlanalves** [comment]
Surely :)
I did the plugin while researching the inner workings of rollup, and at time was too lazy to prepare a build setup. Right now I'm just copying/pasting in the Babel REPL and using the ES5 output 😁 

I've published a new version on npm with the fix and a build step. Thanks a lot for finding it 👍

**Comment by fatfisz** [comment]
You're welcome :smile: I will close the issue and the PR as this is sorted out now.
